setup tools

diff --git a/.github/workflows/check-dist.yml b/.github/workflows/check-dist.yml
--- a/.github/workflows/check-dist.yml
+++ b/.github/workflows/check-dist.yml
@@ -11,11 +11,12 @@ name: Check Transpiled JavaScript
 
 on:
   pull_request:
-    branches:
-      - main
   push:
     branches:
-      - main
+      - master
+
+env:
+  NODE_VERSION: '20'
 
 permissions:
   contents: read
@@ -24,27 +25,35 @@ jobs:
   check-dist:
     name: Check dist/
     runs-on: ubuntu-latest
-
     steps:
-      - name: Checkout
-        id: checkout
+      - name: ⤵️ Check out code from GitHub
         uses: actions/checkout@v4
-
-      - name: Setup Node.js
-        id: setup-node
+      - name: 🏗 Setup Node
         uses: actions/setup-node@v4
         with:
-          node-version-file: .node-version
           cache: npm
+          node-version: ${{ env.NODE_VERSION }}
+      - name: ⤵️ Install Node Dependencies
+        run: |
+          if [[ -f "Makefile" ]]; then
+            MAKEFILE_LIST="$(make -rpn | sed -n -e '/^$/ { n ; /^[^ .#][^ ]*:/ { s/:.*$// ; p ; } ; }')"
+          fi
 
-      - name: Install Dependencies
-        id: install
-        run: npm ci
-
-      - name: Build dist/ Directory
+          if [[ -f "Makefile" ]] && [[ " ${MAKEFILE_LIST[*]} " =~ setup-npm ]]; then
+            echo "installing node dependencies using Makefile...";
+            make setup-npm;
+          elif [[ -f "package-lock.json" ]]; then
+            echo "installing node dependencies using pipeline";
+            npm ci;
+          else
+            red="\e[31m";
+            end_color="\e[0m";
+            echo "${red}lockfile missing - can't install dependencies${end_color}";
+            exit 9;
+          fi
+      - name: 👷 Build dist/ Directory
         id: build
         run: npm run bundle
-
       # This will fail the workflow if the `dist/` directory is different than
       # expected.
       - name: Compare Directories
@@ -60,11 +69,10 @@ jobs:
             git diff --ignore-space-at-eol --text dist/
             exit 1
           fi
-
       # If `dist/` was different than expected, upload the expected version as a
       # workflow artifact.
       - if: ${{ failure() && steps.diff.outcome == 'failure' }}
-        name: Upload Artifact
+        name: ⤴️ Upload Artifact
         id: upload
         uses: actions/upload-artifact@v4
         with:
